name: iOS starter workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: BuildEssentialFeed
        run: |
          xcodebuild -workspace EssentialFeed -scheme EssentialFeed -sdk iphonesimulator -destination ‘platform=iOS Simulator,name=iPhone 7,OS=10.2’ build-for-testing

      - name: BuildEssentialFeediOS
        run: |
          xcodebuild -workspace EssentialFeed -scheme EssentialFeediOS -sdk iphonesimulator -destination ‘platform=iOS Simulator,name=iPhone 7,OS=10.2’ build-for-testing

      - name: TestEssentialFeed
        run: |
          xcodebuild test -workspace EssentialFeed -scheme EssentialFeediOS -sdk iphonesimulator -destination ‘platform=iOS Simulator,name=iPhone 7,OS=10.2’ build-for-testing

      - name: TestEssentialFeediOS
        run: |
          xcodebuild test -workspace EssentialFeed -scheme EssentialFeediOS -sdk iphonesimulator -destination ‘platform=iOS Simulator,name=iPhone 7,OS=10.2’ build-for-testing
